apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-config
  labels:
    app: pgadmin
data:
  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": "PostgreSQL DB",
          "Group": "Servers",
          "Port": "31000",
          "Username": "lena", 
          "Host": "192.168.49.2",   
          "SSLMode": "prefer",
          "MaintenanceDB": "postgres"
        }
      }
    }
