version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: lena
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: messenger
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lena -d messenger"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    image: server-app:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/messenger
      SPRING_DATASOURCE_USERNAME: lena
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      db:
        condition: service_healthy

  client:
    image: nginx:alpine
    volumes:
      - ./client:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    depends_on:
      - server

volumes:
  db-data:
