apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgadmin-data-5gi
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/d/my/HSE/4_course/ПРСП/task_3-4/pgadmin-data"  
